version: '3.8'
services:
  # 1. Contenedor Apache para cargar la carpeta doc (Javadoc)
  web-docs:
    image: httpd:latest
    container_name: minderest-javadoc
    ports:
      - "8082:80"
    volumes:
      - ./productos/doc/apidocs:/usr/local/apache2/htdocs/

  # 2. Contenedor de MySQL con el usuario nuevo
  mysql:
    image: mysql:8.0
    container_name: minderest-mysql
    environment:
      # Password del administrador (root)
      MYSQL_ROOT_PASSWORD: root
      # Nombre de la base de datos inicial
      MYSQL_DATABASE: MINDEREST
    ports:
      - "3307:3306"
    volumes:
      - ./productos/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  # 3. Contenedor de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: minderest-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data: